Адаптивная стилизация главной
htmlacademy-adaptive/1003411-pink-22 pull request #11
Opened 2021-05-02 10:39 UTC by nikbritoff

Артур, прошу обратить внимание на блок с кнопкой загрузки на главной странице. При открытии страницы с шириной экрана почему-то меняется расположение текста под этой кнопкой (писал в телеграме). Если изменить ширину на 1201, например, а потом снова на 1200 без обновления страницы, то все ок.
![photo_2021-04-28_15-43-28](https://user-images.githubusercontent.com/65825157/116810244-6b897700-ab4b-11eb-8c8d-cb6b89103be0.jpg)

Картинки под ретину и иконки переделаю в следующих блоках.

Еще есть вопрос по созданию скошенного фона. Сделал как представляю, но уверен, что это как-то правильнее можно сделать.
![image](https://user-images.githubusercontent.com/65825157/116810311-c4590f80-ab4b-11eb-8b94-55f9b97a21da.png)

2021-05-04 11:01 UTC, wrgraff requested changes
Глюк в Хроме у меня не воспроизводится. Поэтому, сложно сказать в чем причина. Возможно, шрифт сперва фолбечный мелькает и чуть меняет сетку.
Попробуй временно на проекте исключить подключение шрифтов (поставь только sans-serif). И посмотри, осталась ли проблема.
Других идей что-то нет пока.

Смотри какого размера на самом деле эти картинки в шаблоне:
![изображение](https://user-images.githubusercontent.com/37917037/116980925-884eb780-accf-11eb-9ec9-7f4010f12a45.png)

Надо их выдернуть из фрейма и экспортировать такими вот большими =)

Что-то названия картинок скачут несколько. То с подчеркиванием, то с двумя, то дефисы. Как-то странно. По БЭМу что ли называешь их? )
Несколько запутанно выходит, лучше оставлять картинки абстрактными. Они как правило не используются в каком-то одном месте. Например, нет стрелочек на кнопки для отзывов, эти стрелки будут на кнопках всех возможных слайдеров.

2021-05-09 16:21 UTC, nikbritoff reviewed
Не смог победить странные полосы у белых фоновых треугольников
![image](https://user-images.githubusercontent.com/65825157/117579375-3f499980-b0fb-11eb-81bd-eb3b6288cd69.png)

1. Попробовал сделать скругление у таблицы, не уверен в правильности результата.
2. Поигрался с табличкой, но добиться результата как на твоем скрине не удалось( При задании ширины 100% у контейнера, в него помещается вся таблица, а не частично.
![image](https://user-images.githubusercontent.com/65825157/117579501-c4cd4980-b0fb-11eb-921f-885fa6d6cf48.png)



P.S. Названия исправлю в блоке с ретинизацией :)

2021-05-09 21:00 UTC, wrgraff commented on source/sass/blocks/features.scss
> +      url("../img/background-iphone-no-screen.png") no-repeat center top 5px;
Очень уж мудрено.
Было бы хорошо сделать им одинаковые позиции, чтобы их не повторять. ПП можно и пожертвовать немного. Хороший код тут ценнее.
Ну и `no-repeat` точно можно не повторять (а то как-то иронично, что оно повторяется...)

2021-05-09 21:05 UTC, wrgraff commented on source/sass/blocks/features.scss
> +      url("../img/background-iphone-screen-pink.png") no-repeat left 64px top 45px,
Если уж делишь на 2 картинки, почему бы не выжать максимум?
Для телефона нужен png, так как там есть прозрачность. Но скрину экрана это не нужно и эффективнее будет сжатие в jpg

2021-05-09 21:07 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +      url("../img/background-page-header-desktop.png") no-repeat center top;
В блоке с телефонами в совмещении смысл есть: можно использовать 3 картинки поменьше в формате полегче и всего одну png с телефоном.

Но здесь уже в этом нет смысла, это все равно одна из комбинаций. Так что можно и объединить.
На самом деле их и там объединить можно, оно того не стоит, пожалуй.

2021-05-09 21:09 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +    background-position: center top 70px;
Очень запутанно выглядит. Можно же написать просто `center 70px`. Первый параметр за горизонталь, второй за вертикаль отвечает.

2021-05-09 21:13 UTC, wrgraff commented on source/sass/blocks/tariffs.scss
> +  border: 2px solid $gray-200;
Ну этот то радиус работает, а остальные где? )
Ты точно все ролики посмотрел, видел сколько там скруглений? =)

2021-05-13 16:55 UTC, wrgraff approved these changes

2021-05-13 16:55 UTC, wrgraff commented on source/sass/blocks/page-info.scss
> +// }
Закомментированный код не забудь убрать, он по идее вообще в ПР уже не должен попадать, так как ПР —  это правки в "чистовую" версию

2021-05-13 16:56 UTC, merged