Декоративные элементы страницы формы
htmlacademy-adaptive/1003411-pink-22 pull request #12
Opened 2021-05-13 18:46 UTC by nikbritoff

2021-05-14 17:36 UTC, wrgraff requested changes

2021-05-14 17:36 UTC, wrgraff commented on source/sass/blocks/choice-field.scss
> +}
Кажется, и для псевдоэлементов это может быть во многом один и тот же набор правил и для чекбоксов, и для радио.
Когда это 2 совсем разных блока, у нас есть разделение независимое. Но у тебя блок один. И иконки вполне можно ставить разные по модификатору

2021-05-14 17:36 UTC, wrgraff commented on source/sass/blocks/choice-info.scss
> +  margin-bottom: 38px;
Заголовок то по центру должен быть?

А то на десктопе не очень:
![изображение](https://user-images.githubusercontent.com/37917037/118304821-d6459580-b4ef-11eb-9133-62b3eabe8af7.png)

И тут:
![изображение](https://user-images.githubusercontent.com/37917037/118304942-00975300-b4f0-11eb-818b-df6142f20100.png)

2021-05-14 17:36 UTC, wrgraff commented on source/sass/blocks/choice-info.scss
> +      grid-template-columns: 260px 240px 205px;
А нет ощущения, что тут не конкретные размеры колонок, а всегда минимальный размер?
И распределение равномерное по пространству

2021-05-14 17:36 UTC, wrgraff commented on source/sass/blocks/comment.scss
> +  font-family: "Open Sans", "Arial", sans-serif;
Можно же использовать `inherit`. Шрифт поменяется если, то не нужно будет здесь переписывать

2021-05-14 17:36 UTC, wrgraff commented on source/sass/blocks/text-field.scss
> +  background-position: center;
Нюанс в том, что эта плашка-иконка выглядит как часть инпута. И на нее вполне могут ткнуть, ожидая, что инпут сфокусируется.
Надо как-то так придумать, чтобы клик по этой плашке приводил к фокусу на поле.

2021-05-14 22:40 UTC, nikbritoff commented on source/sass/blocks/choice-info.scss
> +  margin-bottom: 38px;
Хм, у меня даже опубликованная версия корректно отображалась..
Добавил text-align: center

2021-05-16 00:03 UTC, wrgraff commented on source/sass/blocks/text-field.scss
> +  .text-field__label::after {
Ну уже логичнее, но как-то неаккуратно при наведении выглядит:
<img width="521" alt="изображение" src="https://user-images.githubusercontent.com/37917037/118381375-e98d5980-b5f2-11eb-8b3a-f10d2172dd41.png">

2021-05-16 00:03 UTC, wrgraff commented on source/sass/blocks/choice-info.scss
> +  margin-bottom: 38px;
Это не поможет )
Посмотри как это работает в браузере Firefox. А то у нас там кроссбраузерность в требованиях =)

2021-05-16 00:07 UTC, wrgraff requested changes
Надо с `legend` разобраться до конца и дорисовать иконки в инпутах )

2021-05-16 12:01 UTC, wrgraff approved these changes

2021-05-16 12:02 UTC, merged